# the list of background files depends on whether we're using ice
_: &bkg_files_ocn
    ocn_filename: MOM.res.nc
_: &bkg_files_ocn_ice
    ice_filename: cice.res.nc
    << : *bkg_files_ocn
_: &bkg_files_ocn_wav
    wav_filename: wav.res.nc
    << : *bkg_files_ocn
_: &bkg_files *bkg_files___DOMAINS__

# the list of correlation operators depends on whether we're using ice
_corr:
  - &corr_ocn {name: ocn, variables: [__DA_VARIABLES_OCN__]}
  - &corr_ice {name: ice, variables: [__DA_VARIABLES_ICE__]}
  - &corr_wav {name: wav, variables: [__DA_VARIABLES_WAV__]}
  - &corr_list_ocn [ *corr_ocn ]
  - &corr_list_ocn_ice [ *corr_ocn , *corr_ice ]
  - &corr_list_ocn_wav [ *corr_ocn , *corr_wav ]

# placeholders used by the obs yaml files that will be placed
#  where _OBSERVATIONS_ token is
_: &obs_distribution RoundRobin
_: &obs_land_mask
  filter: Domain Check
  where:
  - variable: {name: sea_area_fraction@GeoVaLs}
    minvalue: 0.9
_: &observations
    __OBSERVATIONS__

variational:
  minimizer:
    algorithm: RPCG
  iterations:
  - geometry:
      mom6_input_nml: mom_input.nml
      fields metadata: fields_metadata.yaml
    ninner: 150
    gradient norm reduction: 1e-3
    test: on
    diagnostics:
      departures: ombg
    online diagnostics:
      write increment: true
      increment:
        datadir: Data
        date:  &bkg_date __DA_ANA_DATE__
        exp: var.iter1
        type: incr

output:
  datadir: Data
  exp: 3dvar
  type: an

final:
  diagnostics:
    departures: oman

cost function:
  cost type: 3D-Var
  window begin: __DA_WINDOW_START__
  window length: __DA_WINDOW_LENGTH__
  analysis variables: &soca_vars [__DA_VARIABLES__]
  geometry:
    mom6_input_nml: mom_input.nml
    fields metadata: fields_metadata.yaml
  variable change: Ana2Model #Identity
  rotate:
    u: [uocn]
    v: [vocn]

  background:
    read_from_file: 1
    basename: ./bkg/
    date: &bkg_date __DA_ANA_DATE__
    << : *bkg_files
    state variables: [__DA_VARIABLES__, mld, layer_depth]

  background error:
    covariance model: SocaError
    analysis variables:  [__DA_VARIABLES__]
    date: *bkg_date
    bump:
      verbosity: main
      datadir: ./bump
      strategy: specific_univariate
      load_nicas_local: 1
    correlation: *corr_list___DOMAINS__

    variable changes:

    - variable change: VertConvSOCA
      Lz_min: 0.0
      Lz_mld: 0
      Lz_mld_max: 1.0
      scale_layer_thick: 5
      input variables: *soca_vars
      output variables: *soca_vars

    - variable change: BkgErrFILT
      ocean_depth_min: 0    # [m]
      rescale_bkgerr: 1.0
      efold_z: 2500.0       # [m]
      input variables: *soca_vars
      output variables: *soca_vars

    - variable change: BkgErrSOCA
      read_from_file: 3
      basename: ./
      ocn_filename: ocn.bkgerror.nc
      ice_filename: ice.bkgerror.nc
      wav_filename: wav.bkgerror.nc
      date: *bkg_date
      t_min: 0.0
      t_max: 2.5
      s_min: 0.0
      s_max: 0.2
      ssh_min: 0.0 # std ssh=0 => ssh balance applied as
      ssh_max: 0.0 #              strong constraint
      cicen_min: 0.1
      cicen_max: 0.5
      hicen_min: 10.0
      hicen_max: 100.0
      swh_min: 0.1 #0.1 #0.1
      swh_max: 1.5 #10.0 #1.0 #1.50 #0.1
      # TODO test with ocean color
      #chl_min: 0.003
      #chl_max: 10.0
      #biop_min: 0.0
      #biop_max: 1.0e-6
      #fixed_std_sst: 0.005 # OK to create pretty increments
      #fixed_std_sss: 0.001 # but that option should not exist!
      input variables: *soca_vars
      output variables: *soca_vars

    - variable change: HorizFiltSOCA
      niter: 2
      filter variables: *soca_vars
      input variables: *soca_vars
      output variables: *soca_vars

    - variable change: BalanceSOCA
      dsdtmax: 0.1
      dsdzmin: 3.0e-6
      dtdzmin: 1.0e-6
      nlayers: 10
      input variables: *soca_vars
      output variables: *soca_vars


  observations: *observations
